### ISSUE TITLE
I need a FLAG !!!!!

### ISSUE THREAD

**Issue by 3urreka** [tr4l/majestic-bear-ioc#10]
/deploy

**Comment by 3urreka** [comment]
thanks

**Comment by tr4l** [comment]
> thanks

Не волнуйся, мой брат

**Comment by de87684333** [comment]
tu l'as eu ? ?

**Comment by tr4l** [comment]
Никто не получил флаг, ты даже не можешь понять наш рецепт хе-хе-хе
